template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
name-template: $RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
categories:
  - title: ðŸš€ Features
    label: feature
  - title: ðŸ› Bug Fixes
    labels: fix
  - title: ðŸ§° Maintenance
    label: chore
version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch
autolabeler:
  - label: chore
    branch:
      - '/(update|chore)\/.+/'
  - label: fix
    branch:
      - '/fix\/.+/'
  - label: feature
    branch:
      - '/feature\/.+/'
